FPS = 60
GRID_SIZE = 15

SCREEN_HEIGHT = 800 
MAP_SIZE = SCREEN_HEIGHT

SIDEBAR_WIDTH = 200 
SCREEN_WIDTH = MAP_SIZE + SIDEBAR_WIDTH

WIDTH = SCREEN_WIDTH
HEIGHT = SCREEN_HEIGHT

TILE_SIZE = MAP_SIZE // GRID_SIZE
TILE_GRASS = 0
TILE_PATH = 1
TILE_START = 2
TILE_END = 3
