FPS = 60
GRID_SIZE = 10

SCREEN_HEIGHT = 800 
MAP_SIZE = SCREEN_HEIGHT

SIDEBAR_WIDTH = 200 
SCREEN_WIDTH = MAP_SIZE + SIDEBAR_WIDTH

WIDTH = SCREEN_WIDTH
HEIGHT = SCREEN_HEIGHT

TILE_SIZE = MAP_SIZE // GRID_SIZE
TILE_GRASS = 0
TILE_PATH = 1
TILE_START = 2
TILE_END = 3

MENU_BUTTON_COLOR = (0, 100, 0)
MENU_BUTTON_HOVER_COLOR = (0, 180, 0)

BALLOON_SIZE = (30, 40)

SAVE_FILE = "save.json"